version: '3.6'
services:
  php-apache-env:
    container_name: php-apache-env
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./php:/var/www/html
    ports: 
      - 8000:80